export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const SET_USER_FAILURE = "SET_USER_FAILURE";
export const SET_USER_REQUEST = "SET_USER_REQUEST";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const RELEASE_USER = "RELEASE_USER";
export const SET_AUTH = "SET_AUTH";

export const FETCH_SHORTLIST_SUCCESS = "FETCH_SHORTLIST_SUCCESS";
export const FETCH_SHORTLIST_FAILURE = "FETCH_SHORTLIST_FAILURE";
export const FETCH_SHORTLIST_REQUEST = "FETCH_SHORTLIST_REQUEST";

export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const CREATE_UPDATE_REVIEW_SUCCESS = "CREATE_UPDATE_REVIEW_SUCCESS";
export const CREATE_UPDATE_REVIEW_REQUEST = "CREATE_UPDATE_REVIEW_REQUEST";
export const CREATE_UPDATE_REVIEW_FAILURE = "CREATE_UPDATE_REVIEW_FAILURE";

export const FETCH_USER_POST_REVIEW_SUCCESS = "FETCH_USER_POST_REVIEW_SUCCESS";
export const FETCH_USER_POST_REVIEW_REQUEST = "FETCH_USER_POST_REVIEW_REQUEST";
export const FETCH_USER_POST_REVIEW_FAILURE = "FETCH_USER_POST_REVIEW_FAILURE";

export const FETCH_POST_SEARCH_SUCCESS = "FETCH_POST_SEARCH_SUCCESS";
export const FETCH_POST_SEARCH_REQUEST = "FETCH_POST_SEARCH_REQUEST";
export const FETCH_POST_SEARCH_FAILURE = "FETCH_POST_SEARCH_FAILURE";
