# Generated by Django 3.0.5 on 2020-04-06 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200406_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='thumbnail_id',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
