# Generated by Django 3.0.5 on 2020-04-06 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200406_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='thumbnail_id',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_id',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
