# Generated by Django 3.0.5 on 2020-04-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_ingredient_recipestep_recipestepimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestepimage',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='ingredient',
            field=models.ManyToManyField(to='blog.Ingredient'),
        ),
    ]
