# Generated by Django 3.0.5 on 2020-04-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200407_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestepimage',
            name='recipe_step_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blog.RecipeStep'),
        ),
    ]
