# Generated by Django 3.0.5 on 2020-04-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200407_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='post',
        ),
        migrations.RemoveField(
            model_name='recipestepimage',
            name='recipe_step_id',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeStep',
        ),
        migrations.DeleteModel(
            name='RecipeStepImage',
        ),
    ]
