# Generated by Django 3.0.5 on 2020-04-10 05:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200408_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('ml', 'millilitre'), ('L', 'litre'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('tcp', 'teacup'), ('cm', 'centimetre'), ('m', 'metre'), ('g', 'gram'), ('kg', 'kilogram'), ('cup', 'cup')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_id',
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=240)),
                ('ingredient', models.ManyToManyField(to='blog.Ingredient')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_recipesteps', to='blog.Post')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_ingredients', to='blog.Post'),
        ),
    ]
