# Generated by Django 3.0.5 on 2020-04-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200410_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='blog.Post'),
        ),
    ]
