# Generated by Django 3.0.5 on 2020-04-11 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200410_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='description',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('ml', 'millilitre'), ('L', 'litre'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('tcp', 'teacup'), ('cm', 'centimetre'), ('m', 'metre'), ('g', 'gram'), ('kg', 'kilogram'), ('cup', 'cup')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=64),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
