# Generated by Django 3.0.5 on 2020-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200411_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
